### ISSUE TITLE
Error in running dummy dataset

### ISSUE THREAD

**Issue by OzanErcan6** [marco-rudolph/differnet#29]
Output is below:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    train_set, test_set = load_datasets(c.dataset_path, c.class_name)
  File "/home/ozan/differnet/differnet-master/utils.py", line 104, in load_datasets
    trainset = ImageFolderMultiTransform(data_dir_train, transform=transform_train, n_transforms=c.n_transforms)
  File "/home/ozan/differnet/differnet-master/multi_transform_loader.py", line 70, in __init__
    is_valid_file=is_valid_file, n_transforms=n_transforms)
  File "/home/ozan/differnet/differnet-master/multi_transform_loader.py", line 34, in __init__
    classes, class_to_idx = self._find_classes(self.root)
AttributeError: 'ImageFolderMultiTransform' object has no attribute '_find_classes'

**Comment by marco-rudolph** [comment]
For the new torchvision version, use
`classes, class_to_idx = self.find_classes(self.root) `

**Comment by OzanErcan6** [comment]
Thanks that solved !
